### ISSUE TITLE
It crashes i on all the permissions as well

### ISSUE THREAD

**Issue by Beatbgtip** [codehasan/Current-Activity#24]
Crash log
*********************** Crash Head ***********************
Time Of Crash : 16-03-2024 15:35
Device Manufacturer : samsung
Device Model : SM-M315F
Android Version : 12
Android SDK : 31
App VersionName : 1.5.5
App VersionCode : 15

*********************** Crash Log ***********************
java.lang.RuntimeException: Unable to pause activity {io.github.ratul.topactivity/io.github.ratul.topactivity.ui.MainActivity}: java.lang.IllegalArgumentException: io.github.ratul.topactivity: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5639)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5590)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5542)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:47)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.IllegalArgumentException: io.github.ratul.topactivity: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
	at android.app.PendingIntent.getActivitiesAsUser(PendingIntent.java:616)
	at android.app.PendingIntent.getActivities(PendingIntent.java:598)
	at android.app.TaskStackBuilder.getPendingIntent(TaskStackBuilder.java:275)
	at android.app.TaskStackBuilder.getPendingIntent(TaskStackBuilder.java:249)
	at io.github.ratul.topactivity.model.NotificationMonitor.c(Unknown Source:95)
	at io.github.ratul.topactivity.ui.MainActivity.onPause(Unknown Source:10)
	at android.app.Activity.performPause(Activity.java:8485)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1530)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5629)
	... 14 more

**Comment by RokeJulianLockhart** [comment]
Please see https://github.com/codehasan/Current-Activity/issues/25#issuecomment-2183963748 and https://github.com/codehasan/Current-Activity/issues/25#issuecomment-2183963927.

**Comment by Coder-Asura** [comment]
Try the PR I submitted, I hope it can help you！

https://github.com/codehasan/Current-Activity/pull/28

**Comment by codehasan** [comment]
Fixed in v1.5.9, please download from [Releases](https://github.com/codehasan/Current-Activity/releases).
