### ISSUE TITLE
Crash when switching from Current Activity in recent app switcher.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [codehasan/Current-Activity#27]
As the undermentioned depicts, when I switch out of Current Activity (`io.github.ratul.topactivity.ui.MainActivity`) using the stock (QuickStep) app switcher, when I select an application to switch to, Current Activity crashes:

https://github.com/codehasan/Current-Activity/assets/42837531/bd91946e-3bf3-4970-b71d-7c04de1b36cf

However, its floating window remains visible and able to display the class name, although clicking on that class name doesn't actually duplicate it to the clipboard, despite it purporting to.

```log
*********************** Crash Head ***********************
Time Of Crash : 22-06-2024 10:37
Device Manufacturer : Fairphone
Device Model : FP5
Android Version : 13
Android SDK : 33
App VersionName : 1.5.5
App VersionCode : 15

*********************** Crash Log ***********************
java.lang.RuntimeException: Unable to pause activity {io.github.ratul.topactivity/io.github.ratul.topactivity.ui.MainActivity}: java.lang.IllegalArgumentException: io.github.ratul.topactivity: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5065)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5016)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4968)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:48)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: java.lang.IllegalArgumentException: io.github.ratul.topactivity: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:404)
	at android.app.PendingIntent.getActivitiesAsUser(PendingIntent.java:622)
	at android.app.PendingIntent.getActivities(PendingIntent.java:604)
	at android.app.TaskStackBuilder.getPendingIntent(TaskStackBuilder.java:275)
	at android.app.TaskStackBuilder.getPendingIntent(TaskStackBuilder.java:249)
	at io.github.ratul.topactivity.model.NotificationMonitor.c(Unknown Source:95)
	at io.github.ratul.topactivity.ui.MainActivity.onPause(Unknown Source:10)
	at android.app.Activity.performPause(Activity.java:8481)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1619)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5055)
	... 14 more

```

**Comment by Coder-Asura** [comment]
Try the PR I submitted, I hope it can help you！

https://github.com/codehasan/Current-Activity/pull/28

**Comment by RokeJulianLockhart** [comment]
> https://github.com/codehasan/Current-Activity/issues/27#issuecomment-2298219227

@HomeZz, if you can provide a compiled APK, I can evaluate it. I've no build environment. Do we have access to the repository's CI?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/codehasan/Current-Activity/issues/27#issuecomment-2321024328

@HomeZz, you'll want to enable issues on your repository, because my device considers https://github.com/HomeZz/Current-Activity/releases/download/v1.5.9/app-debug-v1.5.9.apk to be "invalid":

> ![image](https://github.com/user-attachments/assets/faec2aa7-4bdf-4c19-b314-9622d1b37f56)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/codehasan/Current-Activity/issues/27#issuecomment-2323941505

@HomeZz, it works perfectly. Many thanks.
