### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by christayloraus** [codehasan/Current-Activity#29]
*********************** Crash Head ***********************
Time Of Crash : 10-08-2024 15:39
Device Manufacturer : samsung
Device Model : SM-F946B
Android Version : 14
Android SDK : 34
App VersionName : 1.5.5
App VersionCode : 15

*********************** Crash Log ***********************
java.lang.RuntimeException: Unable to start service io.github.ratul.topactivity.service.MonitoringService@f9b4e4b with Intent { flg=0x14008000 cmp=io.github.ratul.topactivity/.ui.CrashActivity (has extras) }: java.lang.IllegalArgumentException: io.github.ratul.topactivity: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5286)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2531)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.IllegalArgumentException: io.github.ratul.topactivity: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkPendingIntent(PendingIntent.java:435)
	at android.app.PendingIntent.buildServicePendingIntent(PendingIntent.java:827)
	at android.app.PendingIntent.getService(PendingIntent.java:789)
	at io.github.ratul.topactivity.service.MonitoringService.onTaskRemoved(Unknown Source:27)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5270)
	... 9 more

**Comment by Coder-Asura** [comment]
Try the PR I submitted, I hope it can help you！

https://github.com/codehasan/Current-Activity/pull/28

**Comment by codehasan** [comment]
Fixed in v1.5.9, please download from [Releases](https://github.com/codehasan/Current-Activity/releases).
