### ISSUE TITLE
Crash android 14

### ISSUE THREAD

**Issue by john6778** [codehasan/Current-Activity#30]
*********************** Crash Head ***********************
Time Of Crash : 18-08-2024 22:00
Device Manufacturer : samsung
Device Model : SM-A145F
Android Version : 14
Android SDK : 34
App VersionName : 1.5.8
App VersionCode : 20

*********************** Crash Log ***********************
java.lang.RuntimeException: Unable to pause activity {io.github.ratul.topactivity/io.github.ratul.topactivity.ui.MainActivity}: java.lang.IllegalArgumentException: io.github.ratul.topactivity: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5780)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5731)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5683)
	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:48)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.IllegalArgumentException: io.github.ratul.topactivity: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkPendingIntent(PendingIntent.java:435)
	at android.app.PendingIntent.getActivitiesAsUser(PendingIntent.java:690)
	at android.app.PendingIntent.getActivities(PendingIntent.java:673)
	at android.app.TaskStackBuilder.getPendingIntent(TaskStackBuilder.java:275)
	at android.app.TaskStackBuilder.getPendingIntent(TaskStackBuilder.java:249)
	at io.github.ratul.topactivity.model.NotificationMonitor.c(Unknown Source:95)
	at io.github.ratul.topactivity.ui.MainActivity.onPause(Unknown Source:10)
	at android.app.Activity.performPause(Activity.java:9188)
	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1657)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5770)
	... 14 more

**Comment by Coder-Asura** [comment]
Try the PR I submitted, I hope it can help you！

https://github.com/codehasan/Current-Activity/pull/28

**Comment by NishanModder** [comment]
Fix It

**Comment by aJIEw** [comment]
Same issue in android 15, looks like the author @codehasan haven't responded the issues for a long time, I've forked and created a [debug release](https://github.com/aJIEw/Current-Activity/releases/tag/v1.5.9) for the app, for anyone who can't wait, you can use that for a temporary solution.

**Comment by codehasan** [comment]
Sorry about the late fix. This issue has been fixed in #28 and then further in #57. Please download the latest version v1.5.9 from [Releases](https://github.com/codehasan/Current-Activity/releases).
